version: '3.7'
networks:
  backend:
    driver: bridge
    name: backend
  frontend:
    driver: bridge
    name: frontend
services:
  database:
    image: postgres:12.1-alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
  # The actual server
  api:
    image: discoingroup/discoin
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - backend
    links:
      - database
  # Autoupdate images
  watchtower:
    image: v2tec/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  load_balancer:
    image: caddy/caddy:alpine
    restart: unless-stopped
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy:/var/lib/caddy/.local/share/caddy
    command: ['caddy', 'run', '--config', '/etc/caddy/Caddyfile', '--adapter', 'caddyfile']
    depends_on:
      - api
    links:
      - api
    networks:
      - frontend
      - backend
volumes:
  pgdata:
    external: true
  # Where Caddy stores its certificates
  caddy:
    external: true
