version: '3.7'
networks:
  web:
    name: web
services:
  # Reverse proxy for the server
  reverse-proxy:
    image: caddy/caddy:alpine
    ports:
      # The HTTP port
      - '80:8080'
      # The HTTPS port
      - '443:8443'
    volumes:
      # Config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    command: ['caddy', 'run', '--config', '/etc/caddy/Caddyfile', '--adapter', 'caddyfile']
    networks:
      - web
  # The actual server
  api:
    image: discoingroup/discoin
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    networks:
      - web
  # Autoupdate images
  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
