version: '3.7'
networks:
  web:
    name: web
services:
  # The actual server
  api:
    image: discoingroup/discoin
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    networks:
      - web
  # Autoupdate images
  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
