version: '3.7'
networks:
  backend:
    driver: bridge
    name: backend
services:
  database:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
    networks:
      - backend
  # The actual server
  api:
    image: discoingroup/discoin
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - backend
    links:
      - database
  # Autoupdate images
  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
