version: '3.7'
networks:
  backend:
    driver: bridge
    name: backend
  frontend:
    driver: bridge
    name: frontend
services:
  database:
    image: postgres:12.1-alpine
    restart: unless-stopped
    env_file: .env
    # This should be an `expose` setting but we can't access it externally otherwise
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
  # The actual server
  api:
    image: discoingroup/discoin
    restart: unless-stopped
    env_file: .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`api.localhost`)'
      - 'traefik.http.routers.api.entrypoints=web'
      - 'traefik.http.middlewares.api.compress=true'
      - 'traefik.http.services.api.loadbalancer.server.port=80'
    depends_on:
      - database
    networks:
      - backend
    links:
      - database
  # Autoupdate images
  watchtower:
    image: v2tec/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  traefik:
    image: traefik:v2.1.1
    restart: unless-stopped
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    command:
      [
        '--api.insecure=true',
        '--providers.docker=true',
        '--providers.docker.exposedbydefault=false',
        '--entrypoints.web.address=:80',
      ]
    depends_on:
      - api
    links:
      - api
    networks:
      - frontend
      - backend
  cachet:
    image: cachethq/docker
    restart: unless-stopped
    env_file: cachet.env
    ports:
      - '8000:8000'
    networks:
      - frontend
      - backend
    links:
      - database
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.cachet.rule=Host(`cachet.localhost`)'
      - 'traefik.http.routers.cachet.entrypoints=web'
      - 'traefik.http.middlewares.cachet.compress=true'
      - 'traefik.http.services.cachet.loadbalancer.server.port=8000'
volumes:
  pgdata:
    external: true
